# More info at https://hub.docker.com/r/pierrezemb/gostatic
services:
  gostatic:
    container_name: gostatic
    image: pierrezemb/gostatic:latest
    # edit ports to not conflict with other ports
    ports:
      - "80:8043/tcp"
    # Volumes store your data between container upgrades
    volumes:
      - './gostatic/:/srv/http/'
    restart: unless-stopped